In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

Creating tensors

Scalar Tensor - A tensor with zero dimension

In [3]:
scalar = torch.tensor(42)
print("Scalar tensor: ", scalar)
print("Scalar dimension: ", scalar.ndim)
print("Scalar shape: ", scalar.shape)

Scalar tensor:  tensor(42)
Scalar dimension:  0
Scalar shape:  torch.Size([])


Vector Tensor - 1 dimension tensor

In [4]:
vector = torch.tensor([1,2,3])
print("Vector tensor: ", vector)
print("Vector dimension: ", vector.ndim)
print("Vector shape: ", vector.shape)

Vector tensor:  tensor([1, 2, 3])
Vector dimension:  1
Vector shape:  torch.Size([3])


Matrix Tensor - 2 Dimension

In [5]:
matrix = torch.tensor([[1,2],[3,4]])
print("Matrix tensor: ", matrix)
print("Matrix dimension: ", matrix.ndim)
print("Matrix shape: ", matrix.shape)

Matrix tensor:  tensor([[1, 2],
        [3, 4]])
Matrix dimension:  2
Matrix shape:  torch.Size([2, 2])


Tensor 3 D - more than 2 dimensional

In [6]:
tensor_3d = torch.tensor([
                      [[1,2],[3,4]],
                      [[1,2],[3,4]]
                      ])
print("3D_tensor tensor: ", tensor_3d)
print("3D_tensor dimension: ", tensor_3d.ndim)
print("3D_tensor shape: ", tensor_3d.shape)

3D_tensor tensor:  tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])
3D_tensor dimension:  3
3D_tensor shape:  torch.Size([2, 2, 2])


GPU accerlation

In [9]:
if torch.cuda.is_available():
  gpu_tensor = vector.to('cuda') # moving vector to cuda
  print("Tensor on GPU", gpu_tensor)
else:
  print("Tensor on CPU as CUDA is not available on this machine")

Tensor on GPU tensor([1, 2, 3], device='cuda:0')


Tensor Properties

In [14]:
print("Data type of matrix: ", matrix.dtype)
print("Is matrix on GPU: ", matrix.is_cuda)
print("Matrix avaliable on CUDA: ",matrix.to('cuda'))
print("Matrix size: ", matrix.size())
print("Number of elements in matrix: ", matrix.numel())

Data type of matrix:  torch.int64
Is matrix on GPU:  False
Matrix avaliable on CUDA:  tensor([[1, 2],
        [3, 4]], device='cuda:0')
Matrix size:  torch.Size([2, 2])
Number of elements in matrix:  4


Indexing tensors - selecting specific elements or range of elements from tensor.
Syntax: tensor[row, col]

In [18]:
# Accessing elements in a tensor

tensor = torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print("Dimensions: ", tensor.ndim)
print("Shape: ", tensor.shape)


Dimensions:  2
Shape:  torch.Size([3, 3])


In [19]:
print("Element at (0,1): ",tensor[0,1]) # scalar value

Element at (0,1):  tensor(20)


In [20]:
# 0th row only
tensor[0]

tensor([10, 20, 30])

In [21]:
# all rows but only 0th col
tensor[:,0]

tensor([10, 40, 70])

Slicing

In [23]:
print("First 2 rows: ", tensor[:2])

First 2 rows:  tensor([[10, 20, 30],
        [40, 50, 60]])


In [25]:
print("First 2 cols:\n ", tensor[:, :2])

First 2 cols:
  tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [29]:
print("Middle element:\n ",tensor[1:2, 1:])

Middle element:
  tensor([[50, 60]])


In [32]:
# Fancy indexing 20=(0,1); 90 = (2,2)
print("Get elements 20 and 90: \n", tensor[[0,2],[1,2]]) # [[rows of 2 elements],[corresponding cols]]

Get elements 20 and 90: 
 tensor([20, 90])


In [36]:
# Boolean indexing
mask = tensor > 50
print(mask)

print(tensor[mask]) # values

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [37]:
# changing particular values via indexing
tensor[:,1] = 25
print(tensor)

tensor([[10, 25, 30],
        [40, 25, 60],
        [70, 25, 90]])


In [40]:
tensor[:,0] = torch.tensor([100,400,700])
print(tensor)

tensor([[100,  25,  30],
        [400,  25,  60],
        [700,  25,  90]])


In [44]:
# advanced indexing
indices = torch.tensor([0,2])
print(torch.index_select(tensor, dim = 0, index=indices)) # dim = 0 -> rows, 1 -> cols
print(torch.index_select(tensor, dim = 1, index=indices)) # dim = 1 -> cols

tensor([[100,  25,  30],
        [700,  25,  90]])
tensor([[100,  30],
        [400,  60],
        [700,  90]])


In [45]:
# using tensor with steps
print(tensor[:, ::2])

tensor([[100,  30],
        [400,  60],
        [700,  90]])


In [49]:
# reverse an array
print(torch.flip(tensor, dims=[0]))
print(torch.flip(tensor, dims=[1]))

tensor([[700,  25,  90],
        [400,  25,  60],
        [100,  25,  30]])
tensor([[ 30,  25, 100],
        [ 60,  25, 400],
        [ 90,  25, 700]])
