Tensor DATA TYPES

Base Data Types-
* float - for most deep learning tasks --> memory consumption raises for float16, float 32, float 64. lower precision, faster the speed but float64 is more precise than float32.
* integer - categorical data or indicies
* boolean - mask or logical operations
* complex numbers - for advanced computation

In [1]:
import torch

In [2]:
default_tensor = torch.tensor([1.5, 2.5, 3.5]) # default datatype for pytorch tensor is float32
print(default_tensor.dtype)

torch.float32


In [4]:
float_tensor = torch.tensor([1.5, 2.5, 3.5], dtype=torch.float64)
print(float_tensor.dtype)

torch.float64


In [5]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32) # int32 = general purpose integer
print(int_tensor.dtype)
print(int_tensor)

torch.int32
tensor([1, 2, 3], dtype=torch.int32)


In [6]:
bol_tensor = torch.tensor([True, False, True]) # takes this as boolean automatically, can also be explicitly mentioned using dtype = " "
print(bol_tensor.dtype)


torch.bool


In [7]:
# to convert from 1 datatype to another (float to int)
float_tensor = torch.tensor([1.5, 2.5, 3.5])
print(float_tensor.dtype)
print(float_tensor)

int_tensor = float_tensor.to(torch.int64) # int64 = tensor indices
print(int_tensor.dtype)
print(int_tensor)

torch.float32
tensor([1.5000, 2.5000, 3.5000])
torch.int64
tensor([1, 2, 3])


In [10]:
# int to bool
int_tensor = torch.tensor([0,1,2,0,-1])
bool_tensor = int_tensor.to(torch.bool)
print(bool_tensor.dtype)
print(bool_tensor)

torch.bool
tensor([False,  True,  True, False,  True])


Impact of datatype on memory

In [11]:
float32_tensor = torch.ones(10, dtype=torch.float32) # 32 - bit floating points
float64_tensor = torch.ones(10, dtype=torch.float64) # 64 - bit high precision computation

# tensor.element_size() - gives the size of one element in bytes
# to get total number of memory consumption for the tensor

print(float32_tensor.element_size())
print(float32_tensor.nelement())
print("Memory used by float 32 tensor: ", float32_tensor.element_size()*float32_tensor.nelement(), "bytes") # nelement gives total number of elements in tensor
print(float64_tensor.element_size())
print(float64_tensor.nelement())
print("Memory used by float 64 tensor: ", float64_tensor.element_size()*float64_tensor.nelement(), "bytes")


4
10
Memory used by float 32 tensor:  40
8
10
Memory used by float 64 tensor:  80
