Tensor Manipulation -
Operations that can alter structure, shape or contents of tensors. Eg., reshaping, slicing, joining or spliting, transposing and permutting dimensions.

Reshaping Tensor:
* Reshape
* View

In [ ]:
import torch

In [ ]:
tensor = torch.arange(12) # gives values between 0 and 11
print(tensor)
print(tensor.nelement())
print(tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


Reshape

In [ ]:
# reshaping to 2 x 6

reshape_tensor = tensor.reshape(2, 6)
print(reshape_tensor)
print(reshape_tensor.ndim)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
2


In [ ]:
reshape_tensor_2 = tensor.reshape(3,4)
print(reshape_tensor_2)
print(reshape_tensor_2.ndim)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2


View - requires contiguous memory

In [ ]:
print(tensor.is_contiguous())
flat_tensor = tensor.view(-1) # -1 - pytorch will automatically calculate dimensions
print(flat_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


Slicing - extract specific part of tensors

In [ ]:
tensor_2d = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_2d)
print(tensor_2d.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2


In [ ]:
slice1_tensor = tensor_2d[:1, :]
print(slice1_tensor)

tensor([[1, 2, 3]])


In [ ]:
slice2_tensor = tensor_2d[:, :1]
print(slice2_tensor)

tensor([[1],
        [4],
        [7]])


In [ ]:
slice3_tensor = tensor_2d[1:, 1:]
print(slice3_tensor)
print(slice3_tensor.shape)

tensor([[5, 6],
        [8, 9]])
torch.Size([2, 2])


Joining tensors

* torch.cat() -> merges tensors along an existing dimension.
*



In [ ]:
# torch.cat
tensor_1 = torch.tensor([[1,2],[3,4]])
tensor_2 = torch.tensor([[5,6],[7,8]])
print(tensor_1)
print(tensor_2)
concat_rows = torch.cat((tensor_1, tensor_2), dim =0)
concat_cols = torch.cat((tensor_1, tensor_2), dim =1)
print(concat_rows)
print(concat_cols)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


Stack - creates new dimension and increases tensor's rank

In [ ]:
stack_rows = torch.stack((tensor_1, tensor_2), dim =0) # stacking 1 tensor above or below another tensor
stack_cols = torch.stack((tensor_1, tensor_2), dim =1)
print(tensor_1)
print(tensor_2)
print(stack_rows)
print(stack_rows.shape)
print(stack_cols)
print(stack_cols.shape)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
torch.Size([2, 2, 2])


Splitting - split tensors into smaller chunks

* torch.chunk() - divides tensor into equal sized chunks
* torch.split() - divides uneven splitting based on size



In [ ]:
tensor = torch.arange(12)
chunks = torch.chunk(tensor, 3, dim=0)
print(chunks) # returns iterables

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]))


In [ ]:
splits = torch.split(tensor, 7, dim =0)
print(splits)

(tensor([0, 1, 2, 3, 4, 5, 6]), tensor([ 7,  8,  9, 10, 11]))


Transposing and Permuting

* Transpose - swaps 2 dimensions. eg., n x m -> m x n
* Permute - rearranges all dimension in specific order



In [ ]:
# transpose
tensor_original = torch.arange(24).reshape(12,2) # reshapes tensor to 12 rows and 2 cols
transpose_tensor = torch.transpose(tensor_original, 0, 1)
print(tensor_original)
print(tensor_original.shape)
print(transpose_tensor)
print(transpose_tensor.shape)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
torch.Size([12, 2])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])
torch.Size([2, 12])


In [ ]:
# permute
tensor_original = torch.arange(24).reshape(2,3,4) # reshapes to 2 tensors with 3 rows and 4 cols each
print(tensor_original)
print(tensor_original.shape)

permute_tensor = torch.permute(tensor_original, (2,0,1))
'''
permute - rearranges the dimensions.
Original tensor was reshaped to 2 tensors with 3 rows and 4 cols. (2 x 3 x 4)
Now during permutation we tell torch to bring 2nd index at 0th index, 0th index at 1st index and 1st index at 2nd index. (2, 0, 1) == (4 x 2 x 3)
'''
print(permute_tensor)
print(permute_tensor.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])
torch.Size([4, 2, 3])


Cloning

In [ ]:
import copy

a = [1,2,3]
b = a # stores the address reference of a
print(a)
print(b)

b = copy.deepcopy(a)
print(a)
print(b)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [ ]:
tensor_ones = torch.ones((3,3), requires_grad=True) # pytorch makes sure they are a part of gradient and computation graph
print(tensor_ones)

cloned_tensor = tensor_ones.clone()
print(cloned_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], grad_fn=<CloneBackward0>)


In [ ]:
detached_tensor = tensor_ones.detach()
print(detached_tensor) # detaches tensor from computation graph but assigns a new tensor with the same memory space as original