## View() and Reshape()

- Both helps to change the shape of tensors
- Key differences:
  View() can be used only if tensor is stored in contiguous memory.
  Reshape() - can handle non-contiguous data and tensors, can also create a new copy of tensor if non-c.m
- Contiguous memory - if the original tensor has 2 x 3 matrix, the memory must store it has flattened array, must row it has row major order ( left to right, row by row), performs well
- Non-Contiguous memory - data remains same in memory but the access pattern changes, where indexing becomes computationally expensive

In [1]:
import torch

In [2]:
tensor = torch.arange(12)

In [3]:
view_tensor = tensor.view(2,6)
reshape_tensor = tensor.reshape(2,6)

print(view_tensor)
print(reshape_tensor)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [4]:
# to check whether data is contiguous
tensor.is_contiguous()

True

In [5]:
# when we are not sure about the number of cols needed, mention -1
infered_shape = tensor.view(3,-1) # pytorch will calculate number of cols needed based on number of rows mentioned
print(infered_shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
tensor_3d = tensor.reshape(2,3,-1)
print(tensor_3d)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])


In [11]:
tensor_3d.is_contiguous()

True

In [13]:
print(reshape_tensor)
transpose_tensor = reshape_tensor.t()
print(transpose_tensor)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])


In [15]:
transpose_tensor.is_contiguous()

False

In [18]:
# as it is non_contiguous view() will show an error
error = transpose_tensor.view(2,6)


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [20]:
error = transpose_tensor.reshape(2,6)
print(error)

tensor([[ 0,  6,  1,  7,  2,  8],
        [ 3,  9,  4, 10,  5, 11]])


In [22]:
# to make data contiguous
contiguous_tensor = transpose_tensor.contiguous()
error = contiguous_tensor.view(6,2)
print(error)

tensor([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])
