## Stack Operation
  - The process of combining multiple tensors along a new dimension.
  - 2 of 1 x 4:
  - dim = 0 -> stacking row wise -> 2 x 4 ( 2 rows, 4 cols)
  - dim = 1 -> stacking col wise -> 4 x 2 ( 4 rows, 2 cols)

In [ ]:
import torch

In [ ]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])

print(tensor_1.shape)
print(tensor_1.ndim)

torch.Size([3])
1


In [ ]:
stacked_tensor_0 = torch.stack([tensor_1, tensor_2], dim =0)
print("Shape :",stacked_tensor_0.shape)
print(stacked_tensor_0)

stacked_tensor_1 = torch.stack([tensor_1, tensor_2], dim =1)
print("Shape :",stacked_tensor_1.shape)
print(stacked_tensor_1)

Shape : torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape : torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


Stacking 2D tensors

In [ ]:
tensor2d_1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2d_2 = torch.tensor([[7,8,9],[10,11,12]])
stacked2d_tensor = torch.stack([tensor2d_1, tensor2d_2], dim=0)
print(stacked2d_tensor.shape)
print(stacked2d_tensor)

torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [ ]:
stacked2d_tensor_1 = torch.stack([tensor2d_1, tensor2d_2], dim=1)
print(stacked2d_tensor_1.shape)
print(stacked2d_tensor_1)
''' While stacking 2d tensors through dim = 1, 1st row of both tensors are stacked together.
'''

torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])


In [ ]:
stacked2d_tensor_2 = torch.stack([tensor2d_1, tensor2d_2], dim=2)
print(stacked2d_tensor_2.shape)
print(stacked2d_tensor_2)
'''When dim=2, each elements from both tensors are stacked together '''

torch.Size([2, 3, 2])
tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])


- [1,2] -> dim = 0 = [] ; dim = 1 = 1,2
- [[1,2]] -> dim=0 = [1,2] ; dim = 1 = 1,2 ; dim = 2 = 1,2

In [ ]:
# concat of multiple tensors
concat_tensor = torch.cat((tensor_1, tensor_2), dim=0) # will not add any new dimensions
print("Shape: ", concat_tensor.shape)
print(concat_tensor)

Shape:  torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
concat_tensor_2 = torch.cat((tensor2d_1, tensor2d_2), dim =0)
print("Shape: ", concat_tensor_2.shape)
print(concat_tensor_2)

Shape:  torch.Size([4, 3])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
